### ISSUE TITLE
2 BRR samples in a project

### ISSUE THREAD

**Issue by EdyGH36** [alekmaul/pvsneslib#28] opened 2019-05-17 19:41 UTC
I've loaded 2 BRR sounds into the project
I'm trying to make it play 2 different sounds and there is only 0 value for spcPlaySound(). How can I find out about the sound index to play multiple sounds?

**Comment by hoit** [comment] 2019-05-17 20:21
Hi,

You have 2 types of functions to play sound with pvsneslib (so snesmod lib) :

If you use streaming function, you can only play one sound at the same time. It is the case of spcPlaySound that is a streaming function.

If you want 2 « channels » to play sounds, you need to use functions that doesn’t stream sound like spcEffect.

But it will be more complicated to use because you can’t convert .wav sound to .brr because it works only with streaming functions.
To play sound with spcEffect, you have to embed it in .it file (impulse tracker file, like to play a music) as a sample and convert it to music instead of a sound.
The sound will be loaded in spc memory with spcLoadEffect.

Thank you to drludos who got the same problem and explain it on french forum. :)

If it works for you, do not hesitate to create a new sample which will be useful for the community or create a new wiki page.

**Comment by hoit** [comment] 2019-05-21 19:33
Did you solve your case ? :)

**Comment by EdyGH36** [comment] 2019-05-23 19:32
I have solved the case by using spcSetSoundEntry for each function to switch different sounds.
Another problem is with spcEffect. I've included the sound module file in Soundbank.h

// snesmod soundbank definitions

#ifndef __SOUNDBANK_DEFINITIONS__
#define __SOUNDBANK_DEFINITIONS__

#define MOD_SPCEFFECTTEST          	0

#endif // __SOUNDBANK_DEFINITIONS__

Code:
if (padsCurrent(0) & KEY_L) {
			if (keyLpressed ==0) { 
				keyLpressed = 1;
				// Play effect
				spcLoadEffect (MOD_SPCEFFECTTEST);
				spcFlush();
				spcEffect(8,MOD_SPCEFFECTTEST,15);
				// change background color
				
			}
		}
		else
			keyLpressed = 0;
When testing the ROM and use the spcEffect, it freezes.

**Comment by hoit** [comment] 2019-05-24 04:08
Can you upload here (by dragging and dropping zip file) a minimal project (without unuseful parts) that reproduce the issue?

**Comment by alekmaul** [comment] 2019-05-24 05:25
Regarding samples, there is also the possibility to create a IT file and play the samples from the IT file. I did that for Sydney Hunter

**Comment by EdyGH36** [comment] 2019-05-24 16:20
[sonicsfx.zip](https://github.com/alekmaul/pvsneslib/files/3217760/sonicsfx.zip)

**Comment by EdyGH36** [comment] 2019-05-25 17:47
There you go, hoit.

**Comment by hoit** [comment] 2019-05-26 19:52
i checked it quickly :

In KEY_DOWN condition, you did a mistake. When key is not pressed, you change value of a bad variable. it should be : keydownpressed

For your freeze, you didn't called spcSetBank function. It seems to produce the freeze :
Just add 
spcSetBank(&__SOUNDBANK__);
after
spcAllocateSoundRegion(39);

but the sound doesn't play. I think it is more related to the sound itself.

I advise you to move spcLoadEffect (MOD_SPCEFFECTTEST); before while(1) because it can take some time.

here is a link to initial question from drludos to do the same thing :
https://forums.nesdev.com/viewtopic.php?f=12&t=16818

When finished, this sample will be usefull for everybody !

**Comment by hoit** [comment] 2019-06-03 19:55
EdyGH36 : Did you try with an other sound or find a solution?

**Comment by EdyGH36** [comment] 2019-06-09 16:44
Still freezing after I put the code when you told me...

**Comment by hoit** [comment] 2019-06-10 19:18
[sonicsfx20190610.zip](https://github.com/alekmaul/pvsneslib/files/3273430/sonicsfx20190610.zip)
Did you forget to modify something ?

This is the version with changes i said and it doesn't freeze.
But the sound from .it file doesn't play and i don't know what is the cause. Maybe someone else could help you

**Comment by diegoleao** [comment] 2020-10-15 19:21
@EdyGH36 @hoit I used "Schism tracker" to open the problematic .it file, and then exported its only sample to .wav (alt+t when selecting the sample), but the sample seems to be of 0:00 lenght. I tried other .it files, and they export their sample to wav just fine. I'm still learning, and could be wrong, but I think the .it file is playing "fine", the sample used is the actual problem.

**Comment by hoit** [comment] 2021-01-01 11:38
This post become old and is not related to pvsneslib itself but an issue with the brr file. I propose to close it for clarity reason.

To help people, please check the sample provided by diegoleao [here](https://github.com/alekmaul/pvsneslib/issues/48)

**Closed by hoit** 2021-01-01 11:38 UTC
