### ISSUE TITLE
Error compiling Soundbank

### ISSUE THREAD

**Issue by jeffythedragonslayer** [alekmaul/pvsneslib#134] opened 2023-01-10 01:48 UTC
This doesn't stop me from manually cd'ing into the hello_world dir and building it, but it doesn't look good so I figure I'd let you know about it.

With the shell pointed to /C/pvsneslib/snes-examples,

```
# make
make[1]: Entering directory '/C/pvsneslib/snes-examples/audio'
make[2]: Entering directory '/C/pvsneslib/snes-examples/audio/effects'
Compiling Soundbank ...
/C/pvsneslib//devkitsnes/tools/smconv -s -o res/soundbank -v -b 5 res/effectssfx.it
C:/pvsneslib/devkitsnes/tools/smconv.exe: error while loading shared libraries: ?: cannot open shared object file: No such file or directory
                             make[2]: *** [/C/pvsneslib//devkitsnes/snes_rules:128: res/soundbank.asm] Error 127
make[2]: Leaving directory '/C/pvsneslib/snes-examples/audio/effects'
make[1]: *** [Makefile:3: all] Error 1
make[1]: Leaving directory '/C/pvsneslib/snes-examples/audio'
make: *** [Makefile:6: all] Error 1
```

**Comment by alekmaul** [comment] 2023-01-28 15:12
hum, i can't reproduce it.
could you please explain more your environment (linux, windows, and so on), how you tried to compile it, etc...

**Comment by alekmaul** [comment] 2023-02-04 08:23
If it's not happening anymore, I close the issue

**Closed by alekmaul** 2023-02-04 08:23 UTC
