### ISSUE TITLE
oamSet issue: the sprite disappears when x < 0

### ISSUE THREAD

**Issue by malayli** [alekmaul/pvsneslib#75] opened 2022-01-05 15:05 UTC
This issue is reproducible with this PVSnesLib's sample project: SimpleSprite.

I used the PVSnesLib version 3.4.0.

The sprite disappears when x < 0:
```
oamSet(0, -1, 0, 0, 0, 0, 0, 0);
```

SimpleSprite project when the sprite disappears:
```
#include <snes.h>

extern char gfxpsrite, gfxpsrite_end;
extern char palsprite, palsprite_end;

//---------------------------------------------------------------------------------
int main(void) {
    // Initialize SNES 
	consoleInit();
	
	// Init Sprites gfx and palette with default size of 32x32
	oamInitGfxSet(&gfxpsrite, (&gfxpsrite_end-&gfxpsrite), &palsprite, (&palsprite_end-&palsprite), 0, 0x0000, OBJ_SIZE32_L64);

	// Define sprites parmaters
	oamSet(0, -1, 100, 3, 0, 0, 0, 0); // Put sprite in 100,100, with maximum priority 3 from tile entry 0, palette 0
	oamSetEx(0, OBJ_SMALL, OBJ_SHOW);
	
	// Now Put in 16 color mode and disable all backgrounds
	setMode(BG_MODE1,0); bgSetDisable(0); bgSetDisable(1); bgSetDisable(2);
	setScreenOn();
	
	// Wait for nothing :P
	while(1) {
		// Wait VBL 'and update sprites too ;-) )
		WaitForVBlank();
	}
	return 0;
}
```

**Comment by malayli** [comment] 2022-06-03 07:21
A solution is using `oamSetXY` instead. I close this issue.

**Comment by RetroAntho** [comment] 2022-06-04 12:59
I think we should keep it opened while the issue is not solved. OamSetXY is a workaround but the case should be fixed if possible in oamSet too.
@alekmaul and @malayli what do you think about it?

**Comment by malayli** [comment] 2022-06-04 14:27
@RetroAntho Actually, my understanding is that `oamSet` should be used at level loading time in order to set an initial position for each sprite.
Once the level and the sprites are loaded, `oamSetXY` should be used in the loop to move the sprites.
But I can re-open this issue if @alekmaul agrees.

**Comment by RetroAntho** [comment] 2022-06-07 17:03
You are right @malayli about usage, oamSetXY should be used in this case. It is better to confirm if something can be improved before because as it is, it means that you have to move your sprite to see it with negative positions. Sprites are sometimes used as fixed to improve the design of the map.
I discussed directly with @alekmaul on Discord. In worst case, we will close it later

**Closed** 2023-02-04 08:10 UTC
